version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - auth
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AuthDB
    networks:
      - auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - auth
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
networks:
  auth:

volumes:
  redis_data:
  postgres_data:
  rabbitmq_data: